# Generated by Django 5.1.4 on 2024-12-30 21:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreservices.country')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreservices.country')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreservices.district')),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=False)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreservices.country')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreservices.district')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='coreservices.zone')),
            ],
        ),
    ]
