# Generated by Django 5.1.4 on 2025-01-18 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreservices', '0002_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
