# Generated by Django 5.1.4 on 2025-01-18 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreservices', '0004_trainer_name_alter_trainer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='trainer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreservices.trainer'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coreservices.village'),
        ),
    ]
