# Generated by Django 5.1.4 on 2025-01-18 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreservices', '0005_alter_assignment_trainer_alter_assignment_village'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignment',
            new_name='TrainerAssignment',
        ),
    ]
