# Generated by Django 5.1.4 on 2025-01-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreservices', '0007_role_trainingmodule_remove_trainerassignment_trainer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingmodule',
            name='id',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
