# Generated by Django 5.1.4 on 2025-01-18 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreservices', '0008_alter_trainingmodule_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='country',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
