# Generated by Django 5.1.4 on 2025-01-22 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreservices', '0009_staff_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('sex', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('age_group', models.CharField(blank=True, choices=[('lt_30', 'Less than 30'), ('gte_30', '30 or greater')], max_length=7, null=True)),
                ('phone_1', models.CharField(blank=True, max_length=10, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=10, null=True)),
                ('is_leader', models.BooleanField(default=False)),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='coreservices.village')),
            ],
        ),
    ]
