STAFF_LIST = [
    {
        "username": "admin",
        "email": "admin@test.com",
        "password": "qqqq",
        "first_name": "Admin",
        "last_name": "Test",
        "role": "admin",
    },
    {
        "username": "noroleuser",
        "email": "noroleuser@test.com",
        "password": "qqqq",
        "first_name": "No Role User",
        "last_name": "Test",
    },
    {
        "username": "mltrainer1",
        "email": "mltrainer1@test.com",
        "password": "qqqq",
        "first_name": "ML Trainer 1",
        "last_name": "ML Test 1",
        "role": "trainer",
        "country": "ML",
    },
    {
        "username": "mltrainer2",
        "email": "mltrainer2@test.com",
        "password": "qqqq",
        "first_name": "ML Trainer 2",
        "last_name": "ML Test 2",
        "role": "trainer",
        "country": "ML",
    },
    {
        "username": "mltrainer3",
        "email": "mltrainer3@test.com",
        "password": "qqqq",
        "first_name": "ML Trainer 3",
        "last_name": "ML Test 3",
        "role": "trainer",
        "country": "ML",
    },
    {
        "username": "mltrainer4",
        "email": "mltrainer4@test.com",
        "password": "qqqq",
        "first_name": "ML Trainer 4",
        "last_name": "ML Test 4",
        "role": "trainer",
        "country": "ML",
    },
    {
        "username": "mlplanner1",
        "email": "mlplanner1@test.com",
        "password": "qqqq",
        "first_name": "ML Planner 1",
        "last_name": "ML Test 1",
        "role": "planner",
        "country": "ML",
    },
    {
        "username": "mlplanner2",
        "email": "mlplanner2@test.com",
        "password": "qqqq",
        "first_name": "ML Planner 2",
        "last_name": "ML Test 2",
        "role": "planner",
        "country": "ML",
    },
    {
        "username": "sntrainer1",
        "email": "sntrainer1@test.com",
        "password": "qqqq",
        "first_name": "SN Trainer 1",
        "last_name": "SN Test 1",
        "role": "trainer",
        "country": "SN",
    },
    {
        "username": "sntrainer2",
        "email": "sntrainer2@test.com",
        "password": "qqqq",
        "first_name": "SN Trainer 2",
        "last_name": "SN Test 2",
        "role": "trainer",
        "country": "SN",
    },
    {
        "username": "sntrainer3",
        "email": "sntrainer3@test.com",
        "password": "qqqq",
        "first_name": "SN Trainer 3",
        "last_name": "SN Test 3",
        "role": "trainer",
        "country": "SN",
    },
    {
        "username": "sntrainer4",
        "email": "sntrainer4@test.com",
        "password": "qqqq",
        "first_name": "SN Trainer 4",
        "last_name": "SN Test 4",
        "role": "trainer",
        "country": "SN",
    },
    {
        "username": "snplanner1",
        "email": "snplanner1@test.com",
        "password": "qqqq",
        "first_name": "SN Planner 1",
        "last_name": "SN Test 1",
        "role": "planner",
        "country": "SN",
    },
    {
        "username": "snplanner2",
        "email": "snplanner2@test.com",
        "password": "qqqq",
        "first_name": "SN Planner 2",
        "last_name": "SN Test 2",
        "role": "planner",
        "country": "SN",
    },
    {
        "username": "citrainer1",
        "email": "citrainer1@test.com",
        "password": "qqqq",
        "first_name": "CI Trainer 1",
        "last_name": "CI Test 1",
        "role": "trainer",
        "country": "CI",
    },
    {
        "username": "citrainer2",
        "email": "citrainer2@test.com",
        "password": "qqqq",
        "first_name": "CI Trainer 2",
        "last_name": "CI Test 2",
        "role": "trainer",
        "country": "CI",
    },
    {
        "username": "citrainer3",
        "email": "citrainer3@test.com",
        "password": "qqqq",
        "first_name": "CI Trainer 3",
        "last_name": "CI Test 3",
        "role": "trainer",
        "country": "CI",
    },
    {
        "username": "citrainer4",
        "email": "citrainer4@test.com",
        "password": "qqqq",
        "first_name": "CI Trainer 4",
        "last_name": "CI Test 4",
        "role": "trainer",
        "country": "CI",
    },
    {
        "username": "ciplanner1",
        "email": "ciplanner1@test.com",
        "password": "qqqq",
        "first_name": "CI Planner 1",
        "last_name": "CI Test 1",
        "role": "planner",
        "country": "CI",
    },
    {
        "username": "ciplanner2",
        "email": "ciplanner2@test.com",
        "password": "qqqq",
        "first_name": "CI Planner 2",
        "last_name": "CI Test 2",
        "role": "planner",
        "country": "CI",
    },
]
