MODULE_LIST = [
    {
        "id": "m1_ml",
        "name": "Module 1 - Mali",
        "topic": "Crop Storage",
        "country": "ML",
        "start_date": "2025-01-01",
        "end_date": "2025-01-31",
    },
    {
        "id": "m2_ml",
        "name": "Module 2 - Mali",
        "topic": "Composting",
        "country": "ML",
        "start_date": "2025-02-01",
        "end_date": "2025-02-28",
    },
    {
        "id": "m1_sn",
        "name": "Module 1 - Senegal",
        "topic": "Harvesting",
        "country": "SN",
        "start_date": "2025-01-05",
        "end_date": "2025-02-04",
    },
    {
        "id": "m2_sn",
        "name": "Module 2 - Senegal",
        "topic": "Pest Control",
        "country": "SN",
        "start_date": "2025-02-05",
        "end_date": "2025-03-04",
    },
    {
        "id": "m1_ci",
        "name": "Module 1 - Côte d'Ivoire",
        "topic": "Planting",
        "country": "CI",
        "start_date": "2025-01-10",
        "end_date": "2025-02-09",
    },
    {
        "id": "m2_ci",
        "name": "Module 2 - Côte d'Ivoire",
        "topic": "Fertilization",
        "country": "CI",
        "start_date": "2025-02-10",
        "end_date": "2025-03-09",
    },
]
