# Generated by Django 5.1.4 on 2024-12-26 21:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('server_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingModule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('server_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('server_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=7, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasync.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('server_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=7, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasync.country')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasync.district')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TrainingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('server_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateField()),
                ('scheduled_time', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('training_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasync.trainingmodule')),
                ('village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasync.village')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('server_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('code', models.CharField(max_length=7, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasync.country')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasync.district')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='village',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datasync.zone'),
        ),
    ]
