# Generated by Django 5.1.4 on 2025-01-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingevent',
            name='created_by',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='created_by',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
