# Generated by Django 5.1.4 on 2024-12-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasync', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodule',
            name='code',
            field=models.CharField(default='s', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
