# Generated by Django 5.1.4 on 2025-01-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datasync', '0005_remove_profile_role_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingevent',
            name='is_canceled',
            field=models.BooleanField(default=False),
        ),
    ]
