# Generated by Django 5.1.4 on 2025-01-28 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasync', '0007_participant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='client_id',
            new_name='client',
        ),
    ]
