# Generated by Django 5.1.4 on 2025-03-05 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datasync', '0009_participant_age_group_participant_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='village',
        ),
    ]
