import { appSchema, tableSchema } from "@nozbe/watermelondb";

export default appSchema({
    version: 2,
    tables: [
        tableSchema({
            name: "training_event",
            columns: [
                { name: "created_at", type: "number" },
                { name: "updated_at", type: "number" },
                { name: "created_by", type: "string" },
                { name: "scheduled_for", type: "number" },
                { name: "scheduled_time", type: "string" },
                { name: "is_canceled", type: "boolean", isOptional: true },
                { name: "village", type: "string" },
                { name: "completed_at", type: "number", isOptional: true },
                { name: "location", type: "string", isOptional: true },
                { name: "comments", type: "string", isOptional: true },
                { name: "training_module", type: "string" },
            ],
        }),
        tableSchema({
            name: "participant",
            columns: [
                { name: "created_at", type: "number" },
                { name: "updated_at", type: "number" },
                { name: "created_by", type: "string" },
                { name: "training_event", type: "string" },
                { name: "first_name", type: "string" },
                { name: "last_name", type: "string", isOptional: true },
                { name: "sex", type: "string", isOptional: true },
                { name: "age_group", type: "string", isOptional: true },
                { name: "phone_1", type: "string", isOptional: true },
                { name: "phone_2", type: "string", isOptional: true },
                { name: "client", type: "string", isOptional: true },
                { name: "is_leader", type: "boolean" },
                { name: "village", type: "string" },
                { name: "tombola_tickets", type: "number", isOptional: true },
                { name: "pics_purchased", type: "number", isOptional: true },
                { name: "pics_received", type: "number", isOptional: true },
            ],
        }),
        tableSchema({
            name: "village",
            columns: [
                { name: "name", type: "string" },
                { name: "zone_code", type: "string" },
                { name: "zone_name", type: "string" },
                { name: "district_code", type: "string" },
                { name: "district_name", type: "string" },
                { name: "country_code", type: "string" },
                { name: "country_name", type: "string" },
                { name: "latitude", type: "number" },
                { name: "longitude", type: "number" },
                { name: "is_active", type: "boolean" },
            ],
        }),
        tableSchema({
            name: "client",
            columns: [
                { name: "first_name", type: "string" },
                { name: "last_name", type: "string", isOptional: true },
                { name: "sex", type: "string", isOptional: true },
                { name: "age_group", type: "string", isOptional: true },
                { name: "phone_1", type: "string", isOptional: true },
                { name: "phone_2", type: "string", isOptional: true },
                { name: "is_leader", type: "boolean", isOptional: true },
                { name: "village", type: "string" },
            ],
        }),
        tableSchema({
            name: "training_module",
            columns: [
                { name: "name", type: "string" },
                { name: "topic", type: "string" },
                { name: "country", type: "string" },
                { name: "start_date", type: "number" },
                { name: "end_date", type: "number" },
                { name: "is_active", type: "boolean" },
            ],
        }),
        tableSchema({
            name: "assignment",
            columns: [
                { name: "staff", type: "number" },
                { name: "village", type: "string" },
                { name: "start_date", type: "number" },
                { name: "end_date", type: "number" },
            ],
        }),
        tableSchema({
            name: "staff",
            columns: [
                { name: "country", type: "string" },
                { name: "role_id", type: "string" },
                { name: "role_name", type: "string" },
                { name: "first_name", type: "string" },
                { name: "last_name", type: "string" },
            ],
        }),
    ],
});
